### PR TITLE
fix(login): escape quotes in names

### PR DESCRIPTION
**Pull request by oyo**
## Description

Escape quotes in company names.

## Why

Company names with character " (\&quot;) broke the central custom login theme. We escape them so they get displayed correctly `" -> \"`  

## Issue

n/a

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/14.%20How%20to%20contribute.md)
- [x] I have performed a self-review of my changes
- [x] I have successfully tested my changes

### CODE REVIEW

**Review by JordanGerada3 — APPROVED** [review]
Code looks fine. Tested locally and I confirm company names that contain escape characters are now accepted.

**Comment by oyo** [comment]
> @oyo, this issue with the escape characters only seems to be a problem with the custom themes. For example, the Keycloak base theme handles the escape characters just fine. Is there a way we can handle this in such a fashion, or is your work around our only option you see here?

@JordanGerada3 Keycloak provides a customization machanism using Apache Freemarker (.ftl). It is a simple scripting language that allows composing server side generated pages. The Catena-X central login page is quite different from other login pages that usually render a username+password dialog plus eventually redirecting to a small selection of IdP providers. We have ONLY federated IdPs and a lot of them - that's why we decided to create our own Iogin page from scatch. So we don't bother using anything of the Keycloak UI and use the Freemarker script only to generate a JSON array of all exising IdPs and include our custom JS and CSS that will build the UI from scratch in the user browser. Here the according parts in the source - Keycloak server side executed Freemarker script and client side executed Javascript:

https://github.com/eclipse-tractusx/portal-iam/blob/main/import/keycloak-themes/catenax-central/login/login.ftl#L27-L34
https://github.com/eclipse-tractusx/portal-iam/blob/main/import/keycloak-themes/catenax-central/login/resources/js/Main.js#L274-L282

Since Freemarker is assuming to generate HTML content and not JSON the names are encoded for HTML and not JSON. So a double quote character is output as is not escaped and the client side JSON parser breaks with an error message. In this PR we provide the fix to escape the names manually.

**Comment by JordanGerada3** [comment]
> > @oyo, this issue with the escape characters only seems to be a problem with the custom themes. For example, the Keycloak base theme handles the escape characters just fine. Is there a way we can handle this in such a fashion, or is your work around our only option you see here?
> 
> @JordanGerada3 Keycloak provides a customization machanism using Apache Freemarker (.ftl). It is a simple scripting language that allows composing server side generated pages. The Catena-X central login page is quite different from other login pages that usually render a username+password dialog plus eventually redirecting to a small selection of IdP providers. We have ONLY federated IdPs and a lot of them - that's why we decided to create our own Iogin page from scatch. So we don't bother using anything of the Keycloak UI and use the Freemarker script only to generate a JSON array of all exising IdPs and include our custom JS and CSS that will build the UI from scratch in the user browser. Here the according parts in the source - Keycloak server side executed Freemarker script and client side executed Javascript:
> 
> https://github.com/eclipse-tractusx/portal-iam/blob/main/import/keycloak-themes/catenax-central/login/login.ftl#L27-L34 https://github.com/eclipse-tractusx/portal-iam/blob/main/import/keycloak-themes/catenax-central/login/resources/js/Main.js#L274-L282
> 
> Since Freemarker is assuming to generate HTML content and not JSON the names are encoded for HTML and not JSON. So a double quote character is output as is not escaped and the client side JSON parser breaks with an error message. In this PR we provide the fix to escape the names manually.

@oyo thank you for your response, it makes total sense. Then your solution escaping the quotations client side seems like the go!   
@jjeroch in regards to our conversation last week, please refer to Martins reply. We have a custom filter logic in our implementation where we convert html to json objects. We don't really have another way around this, we need to escape the characters ("") in the frontend within our custom JS.

**Review by JordanGerada3 — APPROVED** [review]
Reviewed and successfully tested locally.

**Review by evegufy — APPROVED** [review]

**Pull request merged**
